[package]
name = "press"
version = "0.1.0"
authors = ["Jared Rodriguez <jared.rodriguez@rackspace.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
